[package]
name = "hello_world"
version = "0.0.1"
authors = [ "Sashka" ]
edition = "2018"

[dependencies]
async-recursion = "0.2"
actix-web = "2.0"
actix-rt = "1.0"
mongodb = "1.0.0"
bson = "1.0.0"
futures = "0.3.5"
chrono = "0.4.11"
serde = { version = "1.0", features = ["derive"] }